# Generated by Django 5.0.6 on 2024-07-04 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userimport'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserImport',
        ),
    ]
