# Generated by Django 5.0.6 on 2024-07-18 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_receipts_show'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='receipts',
            options={'ordering': ['kv'], 'verbose_name': 'Квитанции', 'verbose_name_plural': 'Квитанции'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['kv'], 'verbose_name': 'Пользователи', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AddField(
            model_name='receipts',
            name='ls',
            field=models.IntegerField(blank=True, default=0, verbose_name='Лицевой счет'),
        ),
    ]
