# Generated by Django 5.0.6 on 2024-07-20 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_receipts_options_alter_user_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='check_email',
            field=models.BooleanField(blank=True, default=0, verbose_name='Проверка email'),
        ),
        migrations.AlterField(
            model_name='user',
            name='rec_doc',
            field=models.BooleanField(blank=True, choices=[('0', 'Бумажный'), ('1', 'E-mail')], default=0, verbose_name='Способ получения платежных документов'),
        ),
    ]
