# Generated by Django 5.0.6 on 2024-07-20 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_user_check_email_alter_user_rec_doc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='rec_doc',
            field=models.BooleanField(blank=True, choices=[(False, 'Бумажный'), (True, 'E-mail')], default=False, verbose_name='Способ получения платежных документов'),
        ),
    ]
