# Generated by Django 5.0.6 on 2024-07-21 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_user_rec_doc'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='receipts',
            options={'ordering': ['ls'], 'verbose_name': 'Квитанции', 'verbose_name_plural': 'Квитанции'},
        ),
        migrations.RemoveField(
            model_name='receipts',
            name='kv',
        ),
    ]
