# Generated by Django 5.0.6 on 2024-06-30 03:43

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Заголовок')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Footer Карточку',
                'verbose_name_plural': 'Footer Карточки',
            },
        ),
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Заголовок Информации')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('content', models.TextField(blank=True, verbose_name='Информация')),
                ('file', models.FileField(blank=True, upload_to='files/%Y/%m/%d/', verbose_name='Файл')),
                ('publish', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Создано')),
                ('views', models.IntegerField(default=0, verbose_name='Просмотры')),
            ],
            options={
                'verbose_name': 'Информация о ТСН',
                'verbose_name_plural': 'Информация о ТСН',
                'ordering': ['-publish'],
            },
        ),
        migrations.CreateModel(
            name='KatDoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Заголовок категории')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Категории - Документы',
                'verbose_name_plural': 'Категории - Документы',
            },
        ),
        migrations.CreateModel(
            name='MeterDev',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kv', models.IntegerField(verbose_name='Квартира')),
                ('name', models.CharField(max_length=250, verbose_name='Наименование ПУ')),
                ('number', models.CharField(max_length=100, unique=True, verbose_name='Заводской номер')),
                ('data_pov_next', models.DateField(verbose_name='Дата следующей поверки')),
                ('plomba', models.CharField(blank=True, max_length=100, verbose_name='Пломба')),
                ('amg', models.CharField(blank=True, max_length=100, verbose_name='Антимагнитная пломба')),
                ('pokazaniya', models.CharField(blank=True, max_length=100, verbose_name='Начальные показания')),
                ('date_akt', models.DateField(blank=True, verbose_name='Дата акта')),
                ('type', models.CharField(blank=True, choices=[('hv', 'ХВ'), ('gv', 'ГВ'), ('e', 'ЭЛ')], default='hv', max_length=3, verbose_name='Тип счетчика')),
            ],
            options={
                'verbose_name': 'Прибор учета',
                'verbose_name_plural': 'Приборы учета',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Заголовок новости')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('body', models.TextField(blank=True, verbose_name='Новость')),
                ('publish', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Создано')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('img', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/', verbose_name='Фото')),
                ('file', models.FileField(blank=True, upload_to='files/%Y/%m/%d/', verbose_name='Файл')),
                ('is_publihed', models.BooleanField(default=True, verbose_name='Статус')),
                ('views', models.IntegerField(default=0, verbose_name='Просмотры')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
                'ordering': ['-publish'],
            },
        ),
        migrations.CreateModel(
            name='Pokazaniya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kv', models.IntegerField(verbose_name='Квартира')),
                ('hv', models.CharField(blank=True, max_length=25, verbose_name='Холодная вода')),
                ('gv', models.CharField(blank=True, max_length=25, verbose_name='Горячая вода')),
                ('e', models.CharField(blank=True, max_length=25, verbose_name='Электричество')),
                ('date', models.DateField(verbose_name='Дата показаний')),
            ],
            options={
                'verbose_name': 'Показание ИПУ',
                'verbose_name_plural': 'Показания ИПУ',
            },
        ),
        migrations.CreateModel(
            name='PokazaniyaUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kv', models.IntegerField(verbose_name='Квартира')),
                ('hv', models.CharField(blank=True, max_length=25, verbose_name='Холодная вода')),
                ('gv', models.CharField(blank=True, max_length=25, verbose_name='Горячая вода')),
                ('e', models.CharField(blank=True, max_length=25, verbose_name='Электричество')),
                ('date', models.DateField(verbose_name='Дата показаний')),
            ],
            options={
                'verbose_name': 'Показание собственника',
                'verbose_name_plural': 'Показания собственников',
            },
        ),
        migrations.CreateModel(
            name='UserMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=15, verbose_name='Телефон')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('time_created', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
            ],
            options={
                'verbose_name': 'Сообщения',
                'verbose_name_plural': 'Сообщения',
            },
        ),
        migrations.CreateModel(
            name='Doc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Заголовок')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('content', models.CharField(blank=True, max_length=250, verbose_name='Описание')),
                ('file', models.FileField(blank=True, upload_to='files/%Y/%m/%d/', verbose_name='Файл')),
                ('publish', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Создано')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('views', models.IntegerField(default=0, verbose_name='Просмотры')),
                ('kat_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.katdoc', verbose_name='Категории')),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документы',
                'ordering': ['-publish'],
            },
        ),
    ]
