# Generated by Django 5.0.6 on 2024-07-01 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermessage',
            name='phone',
            field=models.CharField(blank=True, max_length=17, verbose_name='Телефон'),
        ),
    ]
