# Generated by Django 5.0.6 on 2024-07-04 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_usermessage_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokazaniyauser',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='Дата показаний'),
        ),
    ]
