# Generated by Django 5.0.6 on 2024-07-16 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_zayavki'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='zayavki',
            options={'verbose_name': 'Заявку от собственника', 'verbose_name_plural': 'Заявки от собственников'},
        ),
        migrations.AlterField(
            model_name='zayavki',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата заявки'),
        ),
        migrations.AlterField(
            model_name='zayavki',
            name='date_completed',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата выполнения'),
        ),
    ]
