# Generated by Django 5.0.6 on 2024-08-13 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_card_options_alter_doc_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meterdev',
            name='type',
            field=models.CharField(blank=True, choices=[('hv', 'ХВС'), ('gv', 'ГВС'), ('e', 'ЭЛ-ВО')], default='hv', max_length=3, verbose_name='Тип счетчика'),
        ),
    ]
