# Generated by Django 5.0.6 on 2024-08-14 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_alter_usersbot_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersbot',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления лицевого'),
        ),
        migrations.AlterField(
            model_name='usersbot',
            name='kv',
            field=models.IntegerField(verbose_name='Квартира'),
        ),
        migrations.AlterField(
            model_name='usersbot',
            name='ls',
            field=models.IntegerField(verbose_name='Лицевой счет'),
        ),
        migrations.AlterField(
            model_name='usersbot',
            name='user_id',
            field=models.IntegerField(verbose_name='ID Telegram'),
        ),
        migrations.AlterField(
            model_name='usersbot',
            name='username',
            field=models.CharField(blank=True, default=None, max_length=100, verbose_name='Имя пользователя telegram'),
        ),
    ]
