# Generated by Django 5.0.6 on 2024-08-15 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_alter_usersbot_datetime_alter_usersbot_kv_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersbot',
            name='user_id',
            field=models.BigIntegerField(verbose_name='ID Telegram'),
        ),
    ]
