# Generated by Django 5.0.6 on 2024-08-19 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_alter_usersbot_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersbot',
            name='username',
            field=models.CharField(blank=True, max_length=100, verbose_name='Имя пользователя telegram'),
        ),
    ]
