# Generated by Django 5.0.6 on 2024-08-22 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0005_alter_usersbot_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.BigIntegerField()),
                ('last_message_ids', models.JSONField(default=list)),
                ('step', models.IntegerField(default=0)),
                ('kv', models.IntegerField(default=0)),
                ('ls', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterModelOptions(
            name='usersbot',
            options={'verbose_name': 'Пользователя бота', 'verbose_name_plural': 'Пользователи бота'},
        ),
    ]
