# Generated by Django 5.0.6 on 2024-08-22 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0006_userstate_alter_usersbot_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userstate',
            old_name='user',
            new_name='user_id',
        ),
    ]
